app/urls.py
from django.urls import path, include

from .views import *

app_name = 'app'

urlpatterns = [

    path('pay/', pay, name = 'pay'),

]

folder_urlpatterns = [

    path('create-folder/', create_folder, name = 'create-folder'),
    path('get-folder/<uuid:uid>/', get_folder, name = 'get-folder'),
    path('edit-folder/', edit_folder, name = 'edit-folder'),
    path('delete-folder/', delete_folder, name = 'delete-folder'),

    path('add-folder/', add_folder, name = 'add-folder'),
    path('remove-folder/', remove_folder, name = 'remove-folder'),

]

notes_urlpatterns = [

    path('home/', app, name = 'app'),
    path('dom/', home, name = 'home'),

    path('loved/', loved, name = 'loved'),
    path('archive/', archive, name = 'archive'),

    path('trash/', trash, name = 'trash'),
    path('empty-trash', empty_trash, name = 'empty-trash'),

    path('search/', search_notes, name = 'search'),
    path('cancel-search/', cancel_search, name = 'cancel-search'),

]

note_urlpatterns = [

    path('create-note/', create_note, name = 'create-note'),
    path('get-note/<uuid:uid>/', get_note, name = 'get-note'),

    path('love-note/', love_note, name = 'love-note'),
    path('pin-note/', pin_note, name = 'pin-note'),
    path('archive-note/', archive_note, name = 'archive-note'),
    path('delete-note/', delete_note, name = 'delete-note'),

    path('update-contents/', update_contents, name = 'update-contents'),
    path('update-title/', update_title, name = 'update-title'),
    path('update-content/', update_content, name = 'update-content'),

    path('delete-photo/', delete_photo, name = 'delete-photo'),
    path('upload-photo-to-note/',  upload_photo_to_note, name = 'upload-photo-to-note'),

]

urlpatterns += folder_urlpatterns
urlpatterns += notes_urlpatterns
urlpatterns += note_urlpatterns

web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('base.urls')),
    path('', include('analytics.urls')),
    path('', include('user.urls')),
    path('', include('app.urls')),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/templates/components/current-note-photos.html
{% for photo in photos %}

    <div class="photo">
        <input type="text" value="{{ photo.uid }}" hidden />
        <button id="removePhoto">

            <svg xmlns="http://www.w3.org/2000/svg" width="18.008" height="24.68" viewBox="0 0 18.008 24.68">
                <g id="Icon_ionic-ios-trash" data-name="Icon ionic-ios-trash" transform="translate(-8.297 -4.5)">
                  <path id="Контур_3" data-name="Контур 3" d="M9.359,9l1.525,20.44a1.981,1.981,0,0,0,1.894,2.06h9.114a1.981,1.981,0,0,0,1.894-2.06L25.292,9ZM13.34,27.633,12.907,11.25h1.2l.446,16.383Zm4.544,0H16.721V11.25h1.164Zm3.381,0h-1.2L20.5,11.25h1.2Z" transform="translate(0 -2.32)"/>
                  <path id="Контур_4" data-name="Контур 4" d="M24.347,6.469H22L20.283,4.852a1.269,1.269,0,0,0-.861-.352H15.193a1.288,1.288,0,0,0-.874.352L12.6,6.469H10.254A1.733,1.733,0,0,0,8.3,8.3H26.3A1.733,1.733,0,0,0,24.347,6.469Z"/>
                </g>
            </svg>

        </button>
        <img src="{{ photo.file.url }}">
    </div>

{% endfor %}

app/templates/components/current-note.html
<input type="text" id="currentNoteUID" value="{{ note.uid }}"  hidden/>
<input type="text" id="currentNoteTitle" value="{{ note.title }}"  hidden/>
<input type="text" id="currentNoteContent" value="{{ note.content | safe }}" hidden />

{% if note.folders %}

    <div id="currentNoteFolders">

        {% for folder in note.folders.all %}

            <div class="folder">

                <input 
                    type="text"
                    id="folderUID"
                    value="{{ folder.uid }}" 
                    hidden />

                <span>{{ folder.title }}</span>

                <button id="removeFolder">×</button>

            </div>

        {% endfor %}

    </div>

{% endif %}

{% if note.photos %}

    <div id="currentNotePhotos">

        {% for photo in note.photos.all %}

            <div class="photo">
                <input type="text" value="{{ photo.uid }}" hidden />
                <button id="removePhoto">

                    <svg xmlns="http://www.w3.org/2000/svg" width="18.008" height="24.68" viewBox="0 0 18.008 24.68">
                        <g id="Icon_ionic-ios-trash" data-name="Icon ionic-ios-trash" transform="translate(-8.297 -4.5)">
                          <path id="Контур_3" data-name="Контур 3" d="M9.359,9l1.525,20.44a1.981,1.981,0,0,0,1.894,2.06h9.114a1.981,1.981,0,0,0,1.894-2.06L25.292,9ZM13.34,27.633,12.907,11.25h1.2l.446,16.383Zm4.544,0H16.721V11.25h1.164Zm3.381,0h-1.2L20.5,11.25h1.2Z" transform="translate(0 -2.32)"/>
                          <path id="Контур_4" data-name="Контур 4" d="M24.347,6.469H22L20.283,4.852a1.269,1.269,0,0,0-.861-.352H15.193a1.288,1.288,0,0,0-.874.352L12.6,6.469H10.254A1.733,1.733,0,0,0,8.3,8.3H26.3A1.733,1.733,0,0,0,24.347,6.469Z"/>
                        </g>
                    </svg>

                </button>
                <img src="{{ photo.file.url }}">
            </div>
    
        {% endfor %}

    </div>

{% endif %}

app/templates/components/folders.html
{% for folder in folders %}

    <div 
        class="page"
        id="folderSection"
        hx-get="{% url 'app:get-folder' folder.uid %}"
        hx-target=".notes"
        hx-trigger="click, click delay:0.5s">

        <div class="icon">

            <svg xmlns="http://www.w3.org/2000/svg" width="21.364" height="23.313" viewBox="0 0 21.364 23.313">
                <g id="Сгруппировать_1" data-name="Сгруппировать 1" transform="translate(-68 461.1)">
                  <path id="Контур_1" data-name="Контур 1" d="M68-449.349V-437.7h2.444V-461H68Z" transform="translate(0 -0.094)"></path>
                  <path id="Контур_2" data-name="Контур 2" d="M137-449.443v11.657l7.121-.017,7.116-.017.438-.148a3.994,3.994,0,0,0,2.489-2.307c.29-.767.29-.642.273-9.4-.023-9.156.017-8.36-.455-9.315a3.938,3.938,0,0,0-2.347-1.938c-.392-.131-.449-.131-3.166-.154L145.7-461.1l-.011,4.354-.017,4.359-1.176-.943c-.648-.517-1.193-.943-1.211-.943s-.563.426-1.211.943l-1.176.943-.017-4.353-.011-4.353H137Z" transform="translate(-65.078 0)"></path>
                </g>
            </svg>

        </div>

        <input 
            type="text" 
            id="folderUID"
            value="{{ folder.uid }}" 
            hidden />

        <div class="page-title"><span>{{ folder.title }}</span></div>

        <div class="edit-folder-btn-init">

            <svg xmlns="http://www.w3.org/2000/svg" width="24.168" height="24.169" viewBox="0 0 24.168 24.169">
                <path id="Icon_awesome-pencil-alt" data-name="Icon awesome-pencil-alt" d="M23.5,6.71,21.328,8.886a.567.567,0,0,1-.8,0l-5.24-5.24a.567.567,0,0,1,0-.8L17.462.667a2.271,2.271,0,0,1,3.205,0L23.5,3.5A2.262,2.262,0,0,1,23.5,6.71Zm-10.088-2-12.4,12.4-1,5.736a1.134,1.134,0,0,0,1.312,1.312l5.736-1.005,12.4-12.4a.567.567,0,0,0,0-.8l-5.24-5.24a.573.573,0,0,0-.807,0ZM5.859,16.047a.658.658,0,0,1,0-.935l7.27-7.27a.661.661,0,1,1,.935.935l-7.27,7.27a.658.658,0,0,1-.935,0Zm-1.7,3.97H6.421v1.714l-3.045.533L1.908,20.8l.533-3.045H4.155Z" transform="translate(-0.002 -0.005)"/>
            </svg>

        </div>

    </div>

{% endfor %}